<a href="https://colab.research.google.com/github/Amplil/laser/blob/master/laser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [LASER for NLP tasks - Part 2](https://www.engati.com/blog/laser-for-nlp-tasks-part-ii)のページを参考にしたプログラム

## インストール（1度goole driveに保存したら2回目以降は実行する必要ない。）

In [ ]:
#!git clone https://github.com/facebookresearch/LASER

In [2]:
cd "/content/drive/My Drive/Colab Notebooks/LASER_official"

/content/drive/My Drive/Colab Notebooks/LASER_official


In [ ]:
ls

CODE_OF_CONDUCT.md  install_external_tools.sh  remove_external_tools.sh
CONTRIBUTING.md     install_models.sh          source/
data/               LICENSE                    tasks/
docker/             README.md


In [5]:
!export LASER="/content/drive/My Drive/Colab Notebooks/LASER"

In [6]:
!export LASER="${HOME}/projects/laser"

In [ ]:
!bash ./install_models.sh

Please set the environment variable 'LASER'


In [ ]:
# !pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" laserembeddings

In [ ]:
# cd "/content/drive/MyDrive/Colab Notebooks/packages"

In [ ]:
!pip install laserembeddings

     |████████████████████████████████| 51kB 2.9MB/s 
     |████████████████████████████████| 860kB 6.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.35-cp37-none-any.whl size=883999 sha256=af684a18c1283ce0102b03ffb24b68a824e4ad30f538c761294bd24280c31fd8
  Stored in directory: /root/.cache/pip/wheels/63/2a/db/63e2909042c634ef551d0d9ac825b2b0b32dede4a6d87ddc94
Successfully built sacremoses


In [ ]:
!python -m laserembeddings download-models


✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/93langs.fcodes    
✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/93langs.fvocab    
✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/bilstm.93langs.2018-12-26.pt    

✨ You're all set!


In [ ]:
!python -m laserembeddings download-test-data

❌  Looks like you're not running laserembeddings from its source code
     → please checkout https://github.com/yannvgn/laserembeddings.git
       then run "python -m laserembeddings download-test-data" from the root of the repository


In [ ]:
!pytest tests/test_laser.py

============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.6.4, py-1.8.0, pluggy-0.7.1
rootdir: /content, inifile:

========================= no tests ran in 0.00 seconds =========================
ERROR: file not found: tests/test_laser.py



In [40]:
!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" laserembeddings[ja]

     |████████████████████████████████| 15.3MB 327kB/s 
     |████████████████████████████████| 804.1MB 23kB/s 
     |████████████████████████████████| 51kB 2.9MB/s 
     |████████████████████████████████| 860kB 42.0MB/s 
     |████████████████████████████████| 13.4MB 24.3MB/s 
     |████████████████████████████████| 491kB 46.5MB/s 
     |████████████████████████████████| 92kB 5.7MB/s 
     |████████████████████████████████| 307kB 55.9MB/s 
     |████████████████████████████████| 81kB 4.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.35-cp37-none-any.whl size=883999 sha256=6a95152e92818d97348190b836fc6add9fdbd8d9a34d1e25a9b2b9905d9b9feb
  Stored in directory: /root/.cache/pip/wheels/63/2a/db/63e2909042c634ef551d0d9ac825b2b0b32dede4a6d87ddc94
  Created wheel for ipadic: filename=ipadic-1.0.0-cp37-none-any.whl size=13556725 sha256=f6cc306c155efa6611ca10c2bda76f092ebc25cdd81547a85005f43ae28f17dd
  Stored in directory: /root/.cache/pip/wheels/ff/00/d1/0c094a0ce58a77199a0c580

In [41]:
!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" laserembeddings[zh]

  Using cached https://files.pythonhosted.org/packages/7c/19/a16112d4ab9b4ab3933e86f950f882270e30695a286c87877fe846976295/laserembeddings-1.1.1-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/a1/6e/9a9d597dbdd6d0172427c8cc07c35736471e631060df9e59eeb87687f817/transliterate-1.10.2-py2.py3-none-any.whl
Processing /root/.cache/pip/wheels/63/2a/db/63e2909042c634ef551d0d9ac825b2b0b32dede4a6d87ddc94/sacremoses-0.0.35-cp37-none-any.whl
  Using cached https://files.pythonhosted.org/packages/73/ef/8967d406f3f85018ceb5efab50431e901683188f1741ceb053efcab26c87/numpy-1.20.2-cp37-cp37m-manylinux2010_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/74/60/6600a7bc09e7ab38bc53a48a20d8cae49b837f93f5842a41fe513a694912/subword_nmt-0.3.7-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/56/74/6fc9dee50f7c93d6b7d9644554bdc9692f3023fa5d1de779666e6bf8ae76/torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl
     |████████████████████████████████| 19.2M

In [48]:
!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" boto3

     |████████████████████████████████| 133kB 10.9MB/s 
     |████████████████████████████████| 7.4MB 11.6MB/s 
     |████████████████████████████████| 81kB 4.7MB/s 
     |████████████████████████████████| 235kB 37.9MB/s 
     |████████████████████████████████| 153kB 43.1MB/s 
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
ERROR: requests 2.23.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.


## インポート

In [1]:
import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/packages")

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.utils import to_categorical
import re
import pandas as pd
from laserembeddings import Laser

## kaggleのコンペTweet Sentiment Extractionのtest.csvを使う
https://www.kaggle.com/c/tweet-sentiment-extraction/data?select=test.csv

In [ ]:
#df_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/tweet_train.csv', index_col=0).fillna('')
#df_train

keyword  ... target
id             ...       
1              ...      1
4              ...      1
5              ...      1
6              ...      1
7              ...      1
...       ...  ...    ...
10869          ...      1
10870          ...      1
10871          ...      1
10872          ...      1
10873          ...      1

[7613 rows x 4 columns]

In [10]:
df_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/tweet-sentiment-test.csv', index_col=0).fillna('')
df_train

text sentiment
textID                                                                 
f87dea47db  Last session of the day  http://twitpic.com/67ezh   neutral
96d74cb729   Shanghai is also really exciting (precisely -...  positive
eee518ae67  Recession hit Veronique Branquinho, she has to...  negative
01082688c6                                        happy bday!  positive
33987a8ee5             http://twitpic.com/4w75p - I like it!!  positive
...                                                       ...       ...
e5f0e6ef4b  its at 3 am, im very tired but i can`t sleep  ...  negative
416863ce47  All alone in this old house again.  Thanks for...  positive
6332da480c   I know what you mean. My little dog is sinkin...  negative
df1baec676  _sutra what is your next youtube video gonna b...  positive
469e15c5a8   http://twitpic.com/4woj2 - omgssh  ang cute n...  positive

[3534 rows x 2 columns]

In [11]:
#特徴データ
feature = df_train.text
#ラベルデータ
target = df_train.sentiment

In [12]:
#scikit-learnを用いたデータ分割
from sklearn.model_selection import train_test_split
X1, X2, Y1, Y2 = train_test_split(feature, target, test_size=0.3)

In [13]:
X1

textID
6115285ce8                my thoughts dwell on a certain person
771545d181    Loong day. In bed cuddling with papabear and w...
19f108c62c    Hey don`t write yourself off yet. Little girl ...
97cd2255be                  Hi ho  hi ho it`s off to work we go
c3e4e319b8                           I don`t wanna work tonight
                                    ...                        
c5f383c0a0                   I feel so deflated. No more doggy.
5b5be601c2    i think my cold is getting worse, not better!!...
9b46f1ae17                     Thanks, hope you have a good one
8d4c510735     I hope you didn`t take that quote personally!...
77de10258b          Remmber time crisis ? Try it on the #iPhone
Name: text, Length: 2473, dtype: object

In [14]:
Y1

textID
6115285ce8     neutral
771545d181    positive
19f108c62c     neutral
97cd2255be     neutral
c3e4e319b8    negative
                ...   
c5f383c0a0    negative
5b5be601c2    negative
9b46f1ae17    positive
8d4c510735    negative
77de10258b     neutral
Name: sentiment, Length: 2473, dtype: object

In [15]:
from laserembeddings import Laser
laser=Laser()
embeddings = laser.embed_sentences(
    ['let your neural network be polyglot',
     'use multilingual embeddings!'],
    lang='en')  # lang is only used for tokenization
embeddings

array([[0.00156426, 0.01067378, 0.00388247, ..., 0.021797  , 0.00628559,
        0.01434553],
       [0.01456159, 0.00154333, 0.00090701, ..., 0.0148486 , 0.00712933,
        0.04762193]], dtype=float32)

In [26]:
laser=Laser()
embeddings = laser.embed_sentences(
    ['let your neural network be polyglot'],
    lang='en')  # lang is only used for tokenization
embeddings

array([[0.00156426, 0.01067378, 0.00388247, ..., 0.02179701, 0.00628559,
        0.01434553]], dtype=float32)

In [38]:
model=Sequential()
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X1,Y1,validation_data=(X2,Y2),epochs=5)

Epoch 1/5


ValueError: ignored

In [36]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 6         
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X1,Y1,validation_data=(X2,Y2),epochs=5)

In [ ]:
model.save('laser_model.h5')

In [17]:
model=Sequential()
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X1,Y1,validation_data=(X2,Y2),epochs=5)

Epoch 1/5


ValueError: ignored

In [39]:
embeddings = laser.embed_sentences(input_dict,
    lang='en')  # lang is only used for tokenization
embeddings

array([[ 1.7306206e-03,  1.6106192e-03,  6.1235391e-04, ...,
         1.2674484e-02, -1.5845706e-03,  1.1307513e-02],
       [ 9.6531810e-05, -3.2875894e-05,  6.1130075e-04, ...,
         1.0521612e-02, -1.9654762e-03,  8.6358311e-03],
       [ 4.0399139e-03, -1.9150355e-05,  3.3500718e-03, ...,
        -1.1115130e-04, -5.8217230e-03,  1.3894003e-02],
       ...,
       [ 8.7248167e-04, -4.5554538e-04,  1.1702999e-03, ...,
         1.8372232e-02, -4.7760392e-03, -8.9091705e-03],
       [ 3.6770301e-03,  3.2171849e-03,  5.3705910e-04, ...,
         1.2519914e-02, -2.5427695e-03, -2.4180987e-03],
       [ 7.0440792e-03,  1.1275213e-03,  1.1210563e-03, ...,
         2.3967629e-02, -2.8987220e-03,  1.5471232e-02]], dtype=float32)

In [20]:
embedded_dict = {}
for key in input_dict:
    embedded_dict[key] = np.array(get_vect(input_dict[key], lang = key))

NameError: ignored

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(embedded_dict['it'], embedded_dict['es'])

KeyError: ignored

In [22]:
embeddings[0].shape

(1024,)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(embeddings[0], embeddings[1])

ValueError: ignored

In [24]:
embeddings[0]

array([ 0.00173062,  0.00161062,  0.00061235, ...,  0.01267448,
       -0.00158457,  0.01130751], dtype=float32)

# [Multilingual Sentence Models in NLP](https://towardsdatascience.com/multilingual-sentence-models-in-nlp-476f1f246d2f)のページを参考にしたプログラム

In [28]:
import requests
import numpy as np
def get_vect(query_in, lang = 'en', address = '127.0.0.1:8050'):
    url = "http://" + address + "/vectorize"
    params = {"q": query_in, "lang": lang}
    resp = requests.get(url=url, params=params).json()
    return resp["embedding"]

In [29]:
input_dict = {
    "en":"Machine learning isn't as hard as people think.",
    "de":"Maschinelles Lernen ist nicht so schwer wie die Leute denken.",
    "fr":"L'apprentissage automatique n'est pas aussi difficile qu'on le pense.",
    "it":"L'apprendimento automatico non è così difficile come la gente pensa.",
    "es":"El aprendizaje automático no es tan difícil como la gente piensa.",
    "ru":"Машинное обучение не так сложно, как думают люди.",
    "ar":"التعلم الآلي ليس صعبا كما يظن الناس.",
    "pt":"O aprendizado de máquina não é tão difícil quanto as pessoas pensam.",
}

In [30]:
embedded_dict = {}
for key in input_dict:
    embedded_dict[key] = np.array(get_vect(input_dict[key], lang = key))

ConnectionError: ignored

In [31]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(embedded_dict['it'], embedded_dict['es'])

KeyError: ignored

# [laserembeddings · PyPI](https://pypi.org/project/laserembeddings/)のページを参考にしたプログラム

In [42]:
from laserembeddings import Laser

laser = Laser()

# if all sentences are in the same language:

embeddings = laser.embed_sentences(
    ['let your neural network be polyglot',
     'use multilingual embeddings!'],
    lang='en')  # lang is only used for tokenization

# embeddings is a N*1024 (N = number of sentences) NumPy array

In [43]:
embeddings = laser.embed_sentences(
    ['I love pasta.',
     "J'adore les pâtes.",
     'Ich liebe Pasta.'],
    lang=['en', 'fr', 'de'])

In [45]:
%%bash
# DOCS: https://github.com/facebookresearch/LASER/blob/master/install_models.sh

mkdir -p models/laser/
# for FILE in bilstm.eparl21.2018-11-19.pt eparl21.fcodes eparl21.fvocab bilstm.93langs.2018-12-26.pt 93langs.fcodes 93langs.fvocab; do
for FILE in bilstm.93langs.2018-12-26.pt 93langs.fcodes 93langs.fvocab; do
    wget -cq https://dl.fbaipublicfiles.com/laser/models/$FILE -O models/laser/$FILE
done

In [46]:
from laserembeddings import Laser

path_to_bpe_codes = "./models/laser/93langs.fcodes"
path_to_bpe_vocab = "./models/laser/93langs.fvocab"
path_to_encoder ="./models/laser/bilstm.93langs.2018-12-26.pt"

laser = Laser(path_to_bpe_codes, path_to_bpe_vocab, path_to_encoder)

# you can also supply file objects instead of file paths

In [50]:
from io import BytesIO, StringIO
from laserembeddings import Laser
import boto3

s3 = boto3.resource('s3')
MODELS_BUCKET = ...

f_bpe_codes = StringIO(s3.Object(MODELS_BUCKET, path_to_bpe_codes).get()['Body'].read().decode('utf-8'))
f_bpe_vocab = StringIO(s3.Object(MODELS_BUCKET, path_to_bpe_vocab).get()['Body'].read().decode('utf-8'))
f_encoder = BytesIO(s3.Object(MODELS_BUCKET, path_to_encoder).get()['Body'].read())

laser = Laser(f_bpe_codes, f_bpe_vocab, f_encoder)

TypeError: ignored