# [LASER for NLP tasks - Part 2](https://www.engati.com/blog/laser-for-nlp-tasks-part-ii)のページを参考にしたプログラム

In [ ]:
!git clone https://github.com/facebookresearch/LASER

Cloning into 'LASER'...
remote: Enumerating objects: 787, done.
remote: Total 787 (delta 0), reused 0 (delta 0), pack-reused 787
Receiving objects: 100% (787/787), 2.78 MiB | 6.87 MiB/s, done.
Resolving deltas: 100% (303/303), done.
Checking out files: 100% (268/268), done.


In [ ]:
cd "/content/drive/My Drive/Colab Notebooks/LASER"

/content/drive/My Drive/Colab Notebooks/LASER


In [ ]:
ls

CODE_OF_CONDUCT.md  install_external_tools.sh  remove_external_tools.sh
CONTRIBUTING.md     install_models.sh          source/
data/               LICENSE                    tasks/
docker/             README.md


In [ ]:
import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/packages")

In [ ]:
!export LASER="/content/drive/My Drive/Colab Notebooks/LASER"

In [ ]:
!export LASER="${HOME}/projects/laser"

In [ ]:
!bash ./install_models.sh

Please set the environment variable 'LASER'


In [ ]:
!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" laserembeddings

     |████████████████████████████████| 776.8MB 21kB/s 
     |████████████████████████████████| 860kB 43.3MB/s 
     |████████████████████████████████| 51kB 5.0MB/s 
     |████████████████████████████████| 14.8MB 323kB/s 
     |████████████████████████████████| 92kB 10.0MB/s 
     |████████████████████████████████| 307kB 44.0MB/s 
     |████████████████████████████████| 81kB 9.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.35-cp36-none-any.whl size=884000 sha256=cce7f1a2650cd1e32550ab7938f3d79c7f69e41447d88c32b3ac22de7dced7a5
  Stored in directory: /root/.cache/pip/wheels/63/2a/db/63e2909042c634ef551d0d9ac825b2b0b32dede4a6d87ddc94
Successfully built sacremoses
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: nbclient 0.5.1 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.

In [ ]:
cd "/content/drive/MyDrive/Colab Notebooks/packages"

/content/drive/MyDrive/Colab Notebooks/packages


In [ ]:
!python -m laserembeddings download-models


✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/93langs.fcodes    
✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/93langs.fvocab    
✅   Downloaded https://dl.fbaipublicfiles.com/laser/models/bilstm.93langs.2018-12-26.pt    

✨ You're all set!


In [ ]:
from laserembeddings import Laser

In [ ]:
laser=Laser()

In [ ]:
embeddings = laser.embed_sentences(
    ['let your neural network be polyglot',
     'use multilingual embeddings!'],
    lang='en')  # lang is only used for tokenization

In [ ]:
embeddings

array([[0.00156426, 0.01067378, 0.00388246, ..., 0.02179701, 0.0062856 ,
        0.01434554],
       [0.01456156, 0.00154333, 0.00090701, ..., 0.01484862, 0.00712932,
        0.04762192]], dtype=float32)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.utils import to_categorical
import re
import pandas as pd

In [ ]:
input_dict = {
    "en":"Machine learning isn't as hard as people think.",
    "de":"Maschinelles Lernen ist nicht so schwer wie die Leute denken.",
    "fr":"L'apprentissage automatique n'est pas aussi difficile qu'on le pense.",
    "it":"L'apprendimento automatico non è così difficile come la gente pensa.",
    "es":"El aprendizaje automático no es tan difícil como la gente piensa.",
    "ru":"Машинное обучение не так сложно, как думают люди.",
    "ar":"التعلم الآلي ليس صعبا كما يظن الناس.",
    "pt":"O aprendizado de máquina não é tão difícil quanto as pessoas pensam.",
}

In [ ]:
model=Sequential()
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(input_dict,Y1,validation_data=(X2,Y2),epocs=5)

NameError: ignored

In [ ]:
embeddings = laser.embed_sentences(input_dict,
    lang='en')  # lang is only used for tokenization

In [ ]:
embeddings

array([[ 1.73061783e-03,  1.61062076e-03,  6.12359378e-04, ...,
         1.26744611e-02, -1.58457446e-03,  1.13074994e-02],
       [ 9.65321233e-05, -3.28759052e-05,  6.11303025e-04, ...,
         1.05216000e-02, -1.96547760e-03,  8.63582175e-03],
       [ 4.03991621e-03, -1.91513227e-05,  3.35007044e-03, ...,
        -1.11168985e-04, -5.82172116e-03,  1.38939805e-02],
       ...,
       [ 8.72478762e-04, -4.55545320e-04,  1.17029378e-03, ...,
         1.83722302e-02, -4.77604289e-03, -8.90917238e-03],
       [ 3.67702404e-03,  3.21719190e-03,  5.37057873e-04, ...,
         1.25199333e-02, -2.54277000e-03, -2.41810130e-03],
       [ 7.04407878e-03,  1.12752023e-03,  1.12105196e-03, ...,
         2.39676256e-02, -2.89872428e-03,  1.54712228e-02]], dtype=float32)

In [ ]:
embedded_dict = {}
for key in input_dict:
    embedded_dict[key] = np.array(get_vect(input_dict[key], lang = key))

ConnectionError: ignored

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(embedded_dict['it'], embedded_dict['es'])

KeyError: ignored

In [ ]:
embeddings[0].shape

(1024,)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cos_lib = cosine_similarity(embeddings[0], embeddings[1])

ValueError: ignored

In [ ]:
embeddings[0]

array([ 0.00173062,  0.00161062,  0.00061236, ...,  0.01267446,
       -0.00158457,  0.0113075 ], dtype=float32)

# laser embeddings

In [ ]:
# import fasttext
import ftfy
import html
import laserembeddings
import numpy as np
import pandas as pd
import re
import tensorflow as tf
import sys

from fastcache import clru_cache
from laserembeddings import Laser
from typing import List, Union
from urllib.parse import unquote
from sklearn.model_selection import train_test_split

ModuleNotFoundError: ignored

# [kaggleのページ](https://www.kaggle.com/jamesmcguigan/nlp-laser-embeddings-keras)を参考にしたプログラム（直接kaggleの方でもプログラムを実行できる）

In [ ]:
#!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" ftfy

     |████████████████████████████████| 71kB 4.6MB/s 
  Created wheel for ftfy: filename=ftfy-5.9-cp36-none-any.whl size=46451 sha256=fcc79124018a4f01508a736cd620cd5ec175425e5a9fdbd811cd253764affd0c
  Stored in directory: /root/.cache/pip/wheels/5e/2e/f0/b07196e8c929114998f0316894a61c752b63bfa3fdd50d2fc3
Successfully built ftfy


In [ ]:
#!pip install --target "/content/drive/MyDrive/Colab Notebooks/packages" fastcache

  Created wheel for fastcache: filename=fastcache-1.1.0-cp37-cp37m-linux_x86_64.whl size=40119 sha256=96a858db26038b25953c3d4e2d40edf56cca01d0c8e70f320a948bed667eefe4
  Stored in directory: /root/.cache/pip/wheels/6a/80/bf/30024738b03fa5aa521e2a2ac952a8d77d0c65e68d92bcd3b6
Successfully built fastcache


In [ ]:
import sys
sys.path.append("/content/drive/MyDrive/Colab Notebooks/packages")

In [ ]:
# import fasttext
import ftfy
import html
import laserembeddings
import numpy as np
import pandas as pd
import re
import tensorflow as tf
import sys

from fastcache import clru_cache
from laserembeddings import Laser
from typing import List, Union
from urllib.parse import unquote
from sklearn.model_selection import train_test_split

ModuleNotFoundError: ignored